### ISSUE TITLE
need to fix conversation overflowing based on hard token limit

### ISSUE THREAD

**Issue by nollied** [mindflowai/mindflow#104]
the conversation class' `_prune` function is responsible for pruning a conversation's earlier messages to keep a form of chat persistence, but for all conversations (and the current token limits for openai) need to be under 4096 total tokens. something is broken with this mechanism and the earlier message pruning doesn't work.

to fix you need to run `mf history clear` but that just gets rid of all chat persistence.

**Comment by steegecs** [comment]
Fixed!
