### ISSUE TITLE
Cannot run in dev mode getting error  No module named 'mindflow'

### ISSUE THREAD

**Issue by khanakia** [mindflowai/mindflow#118]
I am unable to run the project in development mode 

```
➜  mindflow git:(main) python mindflow/main.py
Traceback (most recent call last):
  File "/Users/khanakia/Downloads/ai/mindflow/mindflow/main.py", line 4, in <module>
    from mindflow.cli.run import cli
ModuleNotFoundError: No module named 'mindflow'
```
![Screenshot 2023-04-09 at 12 28 39 PM](https://user-images.githubusercontent.com/2174170/230759095-9a8ec057-9e4c-4526-8b64-44e0b0e78674.png)

**Comment by steegecs** [comment]
Hi @khanakia! Can you please explain how I can reproduce this error? What command did you run to install, from where, and then how did you run the program?

**Comment by khanakia** [comment]
Hi

i tried running with the following commands
```
python mindflow/main.py
python -m mindflow.main
```

So i modified this file `mindflow/main.py`

```
from mindflow.cli.new_click_cli.cli_main import mindflow_cli

if __name__ == "__main__":
    mindflow_cli()
```

and now it's working when i run `python -m mindflow.main`

So i believe you should update the `mindflow/main.py` or is there another way to run without actually modifying the code ?

**Comment by steegecs** [comment]
Oh - Actually, my bad. It makes sense why this fixed it as this main.py file is no longer used by the CLI once we switched to using click. I think you get the same results by running `mindflow/cli/new_click_cli/cli_main.py` as well. This is the entry using by the command bindings with `mf` and `mindflow` were you to install the package.

**Comment by steegecs** [comment]
Will remove this file in the next release.

**Comment by khanakia** [comment]
I tried running as you suggested that won't work. Can you provide the command so i can run `mindflow/cli/new_click_cli/cli_main.py `
```
➜  mindflow git:(main) ✗ python mindflow/cli/new_click_cli/cli_main.py                
Traceback (most recent call last):
  File "/Users/khanakia/Downloads/ai/mindflow/mindflow/cli/new_click_cli/cli_main.py", line 3, in <module>
    from mindflow.cli.new_click_cli.commands.git.add import add
ModuleNotFoundError: No module named 'mindflow'

➜  mindflow git:(main) ✗ python -m mindflow/cli/new_click_cli.main    
/Library/Frameworks/Python.framework/Versions/3.11/bin/python3: Error while finding module specification for 'mindflow/cli/new_click_cli.main' (ModuleNotFoundError: No module named 'mindflow/cli/new_click_cli')
```

**Comment by steegecs** [comment]
Hmm. Maybe try installing the package with `pip install mindflow` or `pip install -e .` to install locally. Then run `mf` to see if it install properly. A help screen with a list of commands should then show up.

**Comment by steegecs** [comment]
So when I tried to reproduce this locally, I ran into the same issue when I just install `requirement.txt` and then run the program like you did above. Once I ran `pip installl -e .` from the head of the repo, it was able to recognize the mindflow module and it worked.

**Comment by khanakia** [comment]
But how do i run in development mode as i want to make the changes and then test it.

So i will have to reinstall it everytime i make changes to the code ?

**Comment by steegecs** [comment]
No! You should be able to make changes and test if you clone the repo and install with `pip install -e .`. When you run commands with `mf` or `mindflow`, it will execute the code in your cloned repo on your current branch.

**Comment by khanakia** [comment]
Yes i see that thanks
