### ISSUE TITLE
Can I change the openai api endpoint?

### ISSUE THREAD

**Issue by dillfrescott** [mindflowai/mindflow#119]

**Comment by steegecs** [comment]
How do you want to change it?

**Comment by dillfrescott** [comment]
Preferably an env variable I guess

**Comment by dillfrescott** [comment]
Oh, I apologize. I want to use a different endpoint than the api.openai.com one. There are projects that can mimic the openai api and run locally. And I would like to be able to use mindflow with them

**Comment by nollied** [comment]
Oh yeah you should be able to in our code, im not sure how complicated of a task that is but I know @steegecs built us a super general model configurer, and you can select the defaults by modifying the default configurations

**Comment by nollied** [comment]
Here's the service class https://github.com/mindflowai/mindflow/blob/main/mindflow/db/objects/service.py

**Comment by dillfrescott** [comment]
Thank you!
